#
#  Author: Nho Luong
#  Date: 2020-02-23 23:30:14 +0000 (Sun, 23 Feb 2020)
#  Original: H1 2016 (Circle CI 1.x)
#
#

# https://circleci.com/docs/2.0/configuration-reference

version: 2.1
jobs:
  build:
    # technically a docker image is a better choice than machine
    # but we want to introduce some native environment variation
    # between build systems in order to test the repo's build automation is robust
    machine:
      image: default
      #image: ubuntu-1604:201903-01
      # set to an actual docker image when running locally using circle_ci_job.sh
      # docker image must have git installed to do the checkout
      # so using nholuongut/dev:ubuntu instead of base ubuntu image
      #image: nholuongut/dev:ubuntu
    steps:
      - checkout
      - run: setup/ci_bootstrap.sh
      - run: make init
      - run: make
      # to allow docker networking to work
      - run: sudo sysctl net.ipv4.ip_forward=1
      - run: sudo service docker restart
      - run: make test
